insert into carData (id, car_make, car_model, color, mileage, year) values (1, 'Acura', 'TSX', 'Mauv', 121230, 2006);
insert into carData (id, car_make, car_model, color, mileage, year) values (2, 'Toyota', 'Supra', 'Yellow', 132751, 1997);
insert into carData (id, car_make, car_model, color, mileage, year) values (3, 'Mazda', 'B-Series Plus', 'Pink', 118873, 1998);
insert into carData (id, car_make, car_model, color, mileage, year) values (4, 'Volkswagen', 'Eurovan', 'Teal', 147064, 1993);
insert into carData (id, car_make, car_model, color, mileage, year) values (5, 'Jeep', 'Patriot', 'Aquamarine', 5204, 2012);
insert into carData (id, car_make, car_model, color, mileage, year) values (6, 'Geo', 'Storm', 'Turquoise', 93869, 1993);
insert into carData (id, car_make, car_model, color, mileage, year) values (7, 'Toyota', 'Tacoma', 'Pink', 198293, 1996);
insert into carData (id, car_make, car_model, color, mileage, year) values (8, 'Ford', 'E-Series', 'Violet', 131223, 1993);
insert into carData (id, car_make, car_model, color, mileage, year) values (9, 'Pontiac', 'G6', 'Aquamarine', 95178, 2008);
insert into carData (id, car_make, car_model, color, mileage, year) values (10, 'Toyota', 'Corolla', 'Pink', 77397, 1997);
insert into carData (id, car_make, car_model, color, mileage, year) values (11, 'Acura', 'RDX', 'Violet', 67078, 2007);
insert into carData (id, car_make, car_model, color, mileage, year) values (12, 'BMW', 'X6 M', 'Orange', 168272, 2013);
insert into carData (id, car_make, car_model, color, mileage, year) values (13, 'GMC', 'Suburban 2500', 'Purple', 143333, 1998);
insert into carData (id, car_make, car_model, color, mileage, year) values (14, 'Audi', 'TT', 'Mauv', 176779, 2012);
insert into carData (id, car_make, car_model, color, mileage, year) values (15, 'Chrysler', 'Town & Country', 'Teal', 174402, 2012);
insert into carData (id, car_make, car_model, color, mileage, year) values (16, 'Corbin', 'Sparrow', 'Aquamarine', 118513, 2004);
insert into carData (id, car_make, car_model, color, mileage, year) values (17, 'Buick', 'Regal', 'Crimson', 139903, 1995);
insert into carData (id, car_make, car_model, color, mileage, year) values (18, 'Infiniti', 'Q', 'Purple', 115562, 1995);
insert into carData (id, car_make, car_model, color, mileage, year) values (19, 'Mazda', 'RX-7', 'Pink', 22552, 1985);
insert into carData (id, car_make, car_model, color, mileage, year) values (20, 'Chevrolet', '3500', 'Yellow', 171235, 1997);